original_list = [
    "runNumber",
    "eventNumber",
    "mcChannelNumber",
    "RunYear",
    "higgs1Mode",
    "higgs2Mode",
    "nJets_OR",
    "nJets_OR_DL1r_77",
    "HT",
    "HT_lep",
    "HT_jets",
    "met_met",
    "best_Z_Mll",
    "best_Z_other_MtLepMet",
    "best_Z_other_Mll",
    "minOSSFMll",
    "minOSMll",
    "lep_isQMisID_0",
    "lep_isQMisID_1",
    "lep_isQMisID_2",

]

original_kl_list = [
    "mHH",
    "kappaLambda",
    "kLambdaXsecCorrection",
    "kappaLambdaWeight",
    "kappaLambdaWeightError",
]

original_sys_list = [
    "weight_pileup",
    "weight_pileup_UP",
    "weight_pileup_DOWN",
    "jvtSF_customOR__1up",
    "jvtSF_customOR__1down",
    # "tauSFRNNMedium_EFF_ELEOLR_TOTAL_UP",
    # "tauSFRNNLoose_EFF_ELEOLR_TOTAL_UP",
    # "tauSFRNNMedium_EFF_ELEOLR_TOTAL_DOWN",
    # "tauSFRNNLoose_EFF_ELEOLR_TOTAL_DOWN",
    # "tauSFRNNMedium_ELE_EFF_ELEOLR_STAT_UP",
    # "tauSFRNNLoose_ELE_EFF_ELEOLR_STAT_UP",
    # "tauSFRNNMedium_ELE_EFF_ELEOLR_STAT_DOWN",
    # "tauSFRNNLoose_ELE_EFF_ELEOLR_STAT_DOWN",
    # "tauSFRNNMedium_ELE_EFF_ELEOLR_SYST_UP",
    # "tauSFRNNLoose_ELE_EFF_ELEOLR_SYST_UP",
    # "tauSFRNNMedium_ELE_EFF_ELEOLR_SYST_DOWN",
    # "tauSFRNNLoose_ELE_EFF_ELEOLR_SYST_DOWN",
    # "tauSFRNNMedium_EFF_RNNID_1PRONGSTATSYSTPT2025_UP",
    # "tauSFRNNLoose_EFF_RNNID_1PRONGSTATSYSTPT2025_UP",
    # "tauSFRNNMedium_EFF_RNNID_1PRONGSTATSYSTPT2025_DOWN",
    # "tauSFRNNLoose_EFF_RNNID_1PRONGSTATSYSTPT2025_DOWN",
    # "tauSFRNNMedium_EFF_RNNID_1PRONGSTATSYSTPT2530_UP",
    # "tauSFRNNLoose_EFF_RNNID_1PRONGSTATSYSTPT2530_UP",
    # "tauSFRNNMedium_EFF_RNNID_1PRONGSTATSYSTPT2530_DOWN",
    # "tauSFRNNLoose_EFF_RNNID_1PRONGSTATSYSTPT2530_DOWN",
    # "tauSFRNNMedium_EFF_RNNID_1PRONGSTATSYSTPT3040_UP",
    # "tauSFRNNLoose_EFF_RNNID_1PRONGSTATSYSTPT3040_UP",
    # "tauSFRNNMedium_EFF_RNNID_1PRONGSTATSYSTPT3040_DOWN",
    # "tauSFRNNLoose_EFF_RNNID_1PRONGSTATSYSTPT3040_DOWN",
    # "tauSFRNNMedium_EFF_RNNID_1PRONGSTATSYSTPTGE40_UP",
    # "tauSFRNNLoose_EFF_RNNID_1PRONGSTATSYSTPTGE40_UP",
    # "tauSFRNNMedium_EFF_RNNID_1PRONGSTATSYSTPTGE40_DOWN",
    # "tauSFRNNLoose_EFF_RNNID_1PRONGSTATSYSTPTGE40_DOWN",
    # "tauSFRNNMedium_EFF_RNNID_3PRONGSTATSYSTPT2025_UP",
    # "tauSFRNNLoose_EFF_RNNID_3PRONGSTATSYSTPT2025_UP",
    # "tauSFRNNMedium_EFF_RNNID_3PRONGSTATSYSTPT2025_DOWN",
    # "tauSFRNNLoose_EFF_RNNID_3PRONGSTATSYSTPT2025_DOWN",
    # "tauSFRNNMedium_EFF_RNNID_3PRONGSTATSYSTPT2530_UP",
    # "tauSFRNNLoose_EFF_RNNID_3PRONGSTATSYSTPT2530_UP",
    # "tauSFRNNMedium_EFF_RNNID_3PRONGSTATSYSTPT2530_DOWN",
    # "tauSFRNNLoose_EFF_RNNID_3PRONGSTATSYSTPT2530_DOWN",
    # "tauSFRNNMedium_EFF_RNNID_3PRONGSTATSYSTPT3040_UP",
    # "tauSFRNNLoose_EFF_RNNID_3PRONGSTATSYSTPT3040_UP",
    # "tauSFRNNMedium_EFF_RNNID_3PRONGSTATSYSTPT3040_DOWN",
    # "tauSFRNNLoose_EFF_RNNID_3PRONGSTATSYSTPT3040_DOWN",
    # "tauSFRNNMedium_EFF_RNNID_3PRONGSTATSYSTPTGE40_UP",
    # "tauSFRNNLoose_EFF_RNNID_3PRONGSTATSYSTPTGE40_UP",
    # "tauSFRNNMedium_EFF_RNNID_3PRONGSTATSYSTPTGE40_DOWN",
    # "tauSFRNNLoose_EFF_RNNID_3PRONGSTATSYSTPTGE40_DOWN",
    # "tauSFRNNMedium_EFF_RNNID_HIGHPT_UP",
    # "tauSFRNNLoose_EFF_RNNID_HIGHPT_UP",
    # "tauSFRNNMedium_EFF_RNNID_HIGHPT_DOWN",
    # "tauSFRNNLoose_EFF_RNNID_HIGHPT_DOWN",
    # "tauSFRNNMedium_EFF_RNNID_SYST_UP",
    # "tauSFRNNLoose_EFF_RNNID_SYST_UP",
    # "tauSFRNNMedium_EFF_RNNID_SYST_DOWN",
    # "tauSFRNNLoose_EFF_RNNID_SYST_DOWN",
    # "tauSFRNNMedium_EFF_RECO_TOTAL_UP",
    # "tauSFRNNLoose_EFF_RECO_TOTAL_UP",
    # "tauSFRNNMedium_EFF_RECO_TOTAL_DOWN",
    # "tauSFRNNLoose_EFF_RECO_TOTAL_DOWN",
    "lepSF_SF_El_ChargeMisID_LooseAndBLayerLH_FCLoose_STAT_UP_AT",
    "lepSF_SF_El_ChargeMisID_TightLH_FCLoose_STAT_UP_AT",
    "lepSF_SF_El_ChargeMisID_LooseAndBLayerLH_FCLoose_STAT_DOWN_AT",
    "lepSF_SF_El_ChargeMisID_TightLH_FCLoose_STAT_DOWN_AT",
    "lepSF_SF_El_ChargeMisID_LooseAndBLayerLH_FCLoose_SYST_UP_AT",
    "lepSF_SF_El_ChargeMisID_TightLH_FCLoose_SYST_UP_AT",
    "lepSF_SF_El_ChargeMisID_LooseAndBLayerLH_FCLoose_SYST_DOWN_AT",
    "lepSF_SF_El_ChargeMisID_TightLH_FCLoose_SYST_DOWN_AT",
    "lepSF_SF_El_Reco_UP_AT",
    "lepSF_SF_El_Reco_DOWN_AT",
    "lepSF_SF_El_ID_LooseAndBLayerLH_UP_AT",
    "lepSF_SF_El_ID_TightLH_UP_AT",
    "lepSF_SF_El_ID_LooseAndBLayerLH_DOWN_AT",
    "lepSF_SF_El_ID_TightLH_DOWN_AT",
    "lepSF_SF_El_Iso_FCLoose_UP_AT",
    "lepSF_SF_El_Iso_FCLoose_DOWN_AT",
    "lepSF_SF_El_PLVLoose_UP_AT",
    "lepSF_SF_El_PLVLoose_DOWN_AT",
    "lepSF_SF_El_PLVTight_UP_AT",
    "lepSF_SF_El_PLVTight_DOWN_AT",
    "lepSF_SF_Mu_TTVA_STAT_UP_AT",
    "lepSF_SF_Mu_TTVA_STAT_DOWN_AT",
    "lepSF_SF_Mu_TTVA_SYST_UP_AT",
    "lepSF_SF_Mu_TTVA_SYST_DOWN_AT",
    "lepSF_SF_Mu_ID_Loose_STAT_UP_AT",
    "lepSF_SF_Mu_ID_Medium_STAT_UP_AT",
    "lepSF_SF_Mu_ID_Loose_STAT_DOWN_AT",
    "lepSF_SF_Mu_ID_Medium_STAT_DOWN_AT",
    "lepSF_SF_Mu_ID_Loose_SYST_UP_AT",
    "lepSF_SF_Mu_ID_Medium_SYST_UP_AT",
    "lepSF_SF_Mu_ID_Loose_SYST_DOWN_AT",
    "lepSF_SF_Mu_ID_Medium_SYST_DOWN_AT",
    "lepSF_SF_Mu_ID_Loose_STAT_LOWPT_UP_AT",
    "lepSF_SF_Mu_ID_Medium_STAT_LOWPT_UP_AT",
    "lepSF_SF_Mu_ID_Loose_STAT_LOWPT_DOWN_AT",
    "lepSF_SF_Mu_ID_Medium_STAT_LOWPT_DOWN_AT",
    "lepSF_SF_Mu_ID_Loose_SYST_LOWPT_UP_AT",
    "lepSF_SF_Mu_ID_Medium_SYST_LOWPT_UP_AT",
    "lepSF_SF_Mu_ID_Loose_SYST_LOWPT_DOWN_AT",
    "lepSF_SF_Mu_ID_Medium_SYST_LOWPT_DOWN_AT",
    "lepSF_SF_Mu_Iso_FCLoose_SYST_UP_AT",
    "lepSF_SF_Mu_Iso_FCLoose_SYST_DOWN_AT",
    "lepSF_SF_Mu_Iso_FCLoose_STAT_UP_AT",
    "lepSF_SF_Mu_Iso_FCLoose_STAT_DOWN_AT",
    "lepSF_SF_Mu_PLVLoose_SYST_UP_AT",
    "lepSF_SF_Mu_PLVLoose_SYST_DOWN_AT",
    "lepSF_SF_Mu_PLVLoose_STAT_UP_AT",
    "lepSF_SF_Mu_PLVLoose_STAT_DOWN_AT",
    "lepSF_SF_Mu_PLVTight_SYST_UP_AT",
    "lepSF_SF_Mu_PLVTight_SYST_DOWN_AT",
    "lepSF_SF_Mu_PLVTight_STAT_UP_AT",
    "lepSF_SF_Mu_PLVTight_STAT_DOWN_AT",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_0__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_0__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_1__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_1__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_2__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_2__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_3__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_3__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_4__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_4__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_5__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_5__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_6__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_6__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_7__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_7__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_8__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_B_8__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_C_0__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_C_0__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_C_1__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_C_1__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_C_2__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_C_2__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_C_3__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_C_3__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_Light_0__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_Light_0__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_Light_1__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_Light_1__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_Light_2__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_Light_2__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_Light_3__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_Eigen_Light_3__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_extrapolation__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_extrapolation__1up",
    "bTagSF_weight_DL1r_77_FT_EFF_extrapolation_from_charm__1down",
    "bTagSF_weight_DL1r_77_FT_EFF_extrapolation_from_charm__1up",
    "custTrigSF_TightElMediumMuID_FCLooseIso_SLTorDLT_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR__1up",
    "custTrigSF_TightElMediumMuID_FCLooseIso_SLTorDLT_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR__1down",
    "custTrigSF_TightElMediumMuID_FCLooseIso_SLTorDLT_MUON_EFF_TrigStatUncertainty__1up",
    "custTrigSF_TightElMediumMuID_FCLooseIso_SLTorDLT_MUON_EFF_TrigStatUncertainty__1down",
    "custTrigSF_TightElMediumMuID_FCLooseIso_SLTorDLT_MUON_EFF_TrigSystUncertainty__1up",
    "custTrigSF_TightElMediumMuID_FCLooseIso_SLTorDLT_MUON_EFF_TrigSystUncertainty__1down",
    "custTrigSF_TightElMediumMuID_FCLooseIso_SLT_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR__1up",
    "custTrigSF_TightElMediumMuID_FCLooseIso_SLT_EL_EFF_Trigger_TOTAL_1NPCOR_PLUS_UNCOR__1down",
    "custTrigSF_TightElMediumMuID_FCLooseIso_SLT_MUON_EFF_TrigStatUncertainty__1up",
    "custTrigSF_TightElMediumMuID_FCLooseIso_SLT_MUON_EFF_TrigStatUncertainty__1down",
    "custTrigSF_TightElMediumMuID_FCLooseIso_SLT_MUON_EFF_TrigSystUncertainty__1up",
    "custTrigSF_TightElMediumMuID_FCLooseIso_SLT_MUON_EFF_TrigSystUncertainty__1down",
]
